/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDatalogScopeProvider extends DelegatingScopeProvider {
}
