/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.mde.datalog.Assertion;
import org.xtext.mde.datalog.Conditions;
import org.xtext.mde.datalog.DatalogPackage;
import org.xtext.mde.validation.AbstractDatalogValidator;

/**
 * This class contains custom validation rules.
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DatalogValidator extends AbstractDatalogValidator {
  public static final String INVALID_CONDITION = "datalog.INVALID_CONDITION";
  
  public static final String INVALID_ASSERTION = "datalog.INVALID_ASSERTION";
  
  @Check
  public void checkConditionStartsWithLowerCharacter(final Conditions conditions) {
    boolean _isLowerCase = Character.isLowerCase(conditions.getCond().getName().charAt(0));
    boolean _not = (!_isLowerCase);
    if (_not) {
      this.warning("Condition should start with a lower character", conditions, 
        DatalogPackage.Literals.CONDITIONS__COND, 
        DatalogValidator.INVALID_CONDITION);
    }
  }
  
  @Check
  public void checkAssertionStartsWithLowerCharacter(final Assertion assertion) {
    boolean _isLowerCase = Character.isLowerCase(assertion.getTruth().getName().charAt(0));
    boolean _not = (!_isLowerCase);
    if (_not) {
      this.warning("Assertion should start with a lower character", assertion, 
        DatalogPackage.Literals.ASSERTION__TRUTH, 
        DatalogValidator.INVALID_ASSERTION);
    }
  }
}
