/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde;

import org.xtext.mde.AbstractDatalogRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DatalogRuntimeModule extends AbstractDatalogRuntimeModule {
}
