/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mde;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DatalogStandaloneSetup extends DatalogStandaloneSetupGenerated {

	public static void doSetup() {
		new DatalogStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
