/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.validation

import org.eclipse.xtext.validation.Check
import org.xtext.mde.datalog.Assertion
import org.xtext.mde.datalog.Conditions
import org.xtext.mde.datalog.DatalogPackage

/** 
 * This class contains custom validation rules. 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DatalogValidator extends AbstractDatalogValidator { 
		public static val INVALID_CONDITION = 'datalog.INVALID_CONDITION'
		public static val INVALID_ASSERTION = 'datalog.INVALID_ASSERTION'
		
	
		@Check
		def checkConditionStartsWithLowerCharacter(Conditions conditions) {
			if(!Character.isLowerCase(conditions.cond.name.charAt(0))) {
				warning('Condition should start with a lower character', conditions, 
						DatalogPackage.Literals.CONDITIONS__COND,
						INVALID_CONDITION);
			}
		}
		
		@Check
		def checkAssertionStartsWithLowerCharacter(Assertion assertion) {
			if(!Character.isLowerCase(assertion.truth.name.charAt(0))) {
				warning('Assertion should start with a lower character', assertion, 
						DatalogPackage.Literals.ASSERTION__TRUTH,
						INVALID_ASSERTION);
			}
		}
}
