/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assertion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.Assertion#getTruth <em>Truth</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.Assertion#getDot <em>Dot</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getAssertion()
 * @model
 * @generated
 */
public interface Assertion extends EObject
{
  /**
   * Returns the value of the '<em><b>Truth</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Truth</em>' containment reference.
   * @see #setTruth(Atom)
   * @see org.xtext.mde.datalog.DatalogPackage#getAssertion_Truth()
   * @model containment="true"
   * @generated
   */
  Atom getTruth();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Assertion#getTruth <em>Truth</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Truth</em>' containment reference.
   * @see #getTruth()
   * @generated
   */
  void setTruth(Atom value);

  /**
   * Returns the value of the '<em><b>Dot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dot</em>' attribute.
   * @see #setDot(String)
   * @see org.xtext.mde.datalog.DatalogPackage#getAssertion_Dot()
   * @model
   * @generated
   */
  String getDot();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Assertion#getDot <em>Dot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dot</em>' attribute.
   * @see #getDot()
   * @generated
   */
  void setDot(String value);

} // Assertion
