/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assertion Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.AssertionMinus#getCheck <em>Check</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.AssertionMinus#getDot <em>Dot</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getAssertionMinus()
 * @model
 * @generated
 */
public interface AssertionMinus extends EObject
{
  /**
   * Returns the value of the '<em><b>Check</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Check</em>' containment reference.
   * @see #setCheck(FormulaC)
   * @see org.xtext.mde.datalog.DatalogPackage#getAssertionMinus_Check()
   * @model containment="true"
   * @generated
   */
  FormulaC getCheck();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.AssertionMinus#getCheck <em>Check</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Check</em>' containment reference.
   * @see #getCheck()
   * @generated
   */
  void setCheck(FormulaC value);

  /**
   * Returns the value of the '<em><b>Dot</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dot</em>' attribute.
   * @see #setDot(String)
   * @see org.xtext.mde.datalog.DatalogPackage#getAssertionMinus_Dot()
   * @model
   * @generated
   */
  String getDot();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.AssertionMinus#getDot <em>Dot</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dot</em>' attribute.
   * @see #getDot()
   * @generated
   */
  void setDot(String value);

} // AssertionMinus
