/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.Formula#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.Formula#getComma <em>Comma</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.Formula#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getFormula()
 * @model
 * @generated
 */
public interface Formula extends FormulaC
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(FormulaC)
   * @see org.xtext.mde.datalog.DatalogPackage#getFormula_Left()
   * @model containment="true"
   * @generated
   */
  FormulaC getLeft();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Formula#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(FormulaC value);

  /**
   * Returns the value of the '<em><b>Comma</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comma</em>' attribute.
   * @see #setComma(String)
   * @see org.xtext.mde.datalog.DatalogPackage#getFormula_Comma()
   * @model
   * @generated
   */
  String getComma();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Formula#getComma <em>Comma</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comma</em>' attribute.
   * @see #getComma()
   * @generated
   */
  void setComma(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(AtomC)
   * @see org.xtext.mde.datalog.DatalogPackage#getFormula_Right()
   * @model containment="true"
   * @generated
   */
  AtomC getRight();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Formula#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(AtomC value);

} // Formula
