/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.Statements#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.Statements#getAssertion <em>Assertion</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getStatements()
 * @model
 * @generated
 */
public interface Statements extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Conditions)
   * @see org.xtext.mde.datalog.DatalogPackage#getStatements_Condition()
   * @model containment="true"
   * @generated
   */
  Conditions getCondition();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Statements#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Conditions value);

  /**
   * Returns the value of the '<em><b>Assertion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assertion</em>' containment reference.
   * @see #setAssertion(Assertion)
   * @see org.xtext.mde.datalog.DatalogPackage#getStatements_Assertion()
   * @model containment="true"
   * @generated
   */
  Assertion getAssertion();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Statements#getAssertion <em>Assertion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assertion</em>' containment reference.
   * @see #getAssertion()
   * @generated
   */
  void setAssertion(Assertion value);

} // Statements
