/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stmt Plus Minus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.StmtPlusMinus#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.StmtPlusMinus#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getStmtPlusMinus()
 * @model
 * @generated
 */
public interface StmtPlusMinus extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(StmtPlus)
   * @see org.xtext.mde.datalog.DatalogPackage#getStmtPlusMinus_Left()
   * @model containment="true"
   * @generated
   */
  StmtPlus getLeft();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.StmtPlusMinus#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(StmtPlus value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(StmtMinus)
   * @see org.xtext.mde.datalog.DatalogPackage#getStmtPlusMinus_Right()
   * @model containment="true"
   * @generated
   */
  StmtMinus getRight();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.StmtPlusMinus#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(StmtMinus value);

} // StmtPlusMinus
