/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stmt Plus</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.StmtPlus#getPlus <em>Plus</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.StmtPlus#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.StmtPlus#getRightPlus <em>Right Plus</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getStmtPlus()
 * @model
 * @generated
 */
public interface StmtPlus extends EObject
{
  /**
   * Returns the value of the '<em><b>Plus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plus</em>' attribute.
   * @see #setPlus(String)
   * @see org.xtext.mde.datalog.DatalogPackage#getStmtPlus_Plus()
   * @model
   * @generated
   */
  String getPlus();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.StmtPlus#getPlus <em>Plus</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plus</em>' attribute.
   * @see #getPlus()
   * @generated
   */
  void setPlus(String value);

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(StmtPlus)
   * @see org.xtext.mde.datalog.DatalogPackage#getStmtPlus_Left()
   * @model containment="true"
   * @generated
   */
  StmtPlus getLeft();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.StmtPlus#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(StmtPlus value);

  /**
   * Returns the value of the '<em><b>Right Plus</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right Plus</em>' containment reference.
   * @see #setRightPlus(Statements)
   * @see org.xtext.mde.datalog.DatalogPackage#getStmtPlus_RightPlus()
   * @model containment="true"
   * @generated
   */
  Statements getRightPlus();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.StmtPlus#getRightPlus <em>Right Plus</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right Plus</em>' containment reference.
   * @see #getRightPlus()
   * @generated
   */
  void setRightPlus(Statements value);

} // StmtPlus
