/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DatalogUiModule extends AbstractDatalogUiModule {

	public DatalogUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
