/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.ide;

import org.xtext.mde.ide.AbstractDatalogIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DatalogIdeModule extends AbstractDatalogIdeModule {
}
