/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.mde.datalog.Ask;
import org.xtext.mde.datalog.DatalogPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ask</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AskImpl extends StatementsImpl implements Ask
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AskImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DatalogPackage.Literals.ASK;
  }

} //AskImpl
