/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.mde.Dlg.ui.internal.DlgActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DatalogExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DlgActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DlgActivator activator = DlgActivator.getInstance();
		return activator != null ? activator.getInjector(DlgActivator.ORG_XTEXT_MDE_DATALOG) : null;
	}

}
