/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atom</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getAtom()
 * @model
 * @generated
 */
public interface Atom extends Form, Formula
{
} // Atom
