/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.Conditions#getCond <em>Cond</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.Conditions#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getConditions()
 * @model
 * @generated
 */
public interface Conditions extends Statements
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Atom)
   * @see org.xtext.mde.datalog.DatalogPackage#getConditions_Cond()
   * @model containment="true"
   * @generated
   */
  Atom getCond();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Conditions#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Atom value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Formula)
   * @see org.xtext.mde.datalog.DatalogPackage#getConditions_Right()
   * @model containment="true"
   * @generated
   */
  Formula getRight();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Conditions#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Formula value);

} // Conditions
