/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.mde.datalog.DatalogFactory
 * @model kind="package"
 * @generated
 */
public interface DatalogPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "datalog";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/mde/Datalog";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "datalog";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DatalogPackage eINSTANCE = org.xtext.mde.datalog.impl.DatalogPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.ModelImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Program</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROGRAM = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.StatementsImpl <em>Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.StatementsImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getStatements()
   * @generated
   */
  int STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.CommentImpl <em>Comment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.CommentImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getComment()
   * @generated
   */
  int COMMENT = 2;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMENT__TEXT = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Comment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMENT_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.FormImpl <em>Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.FormImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getForm()
   * @generated
   */
  int FORM = 3;

  /**
   * The number of structural features of the '<em>Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.AssertionImpl <em>Assertion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.AssertionImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getAssertion()
   * @generated
   */
  int ASSERTION = 4;

  /**
   * The number of structural features of the '<em>Assertion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTION_FEATURE_COUNT = STATEMENTS_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.FormulaImpl <em>Formula</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.FormulaImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getFormula()
   * @generated
   */
  int FORMULA = 5;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA__LEFT = ASSERTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA__RIGHT = ASSERTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Formula</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_FEATURE_COUNT = ASSERTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.AtomImpl <em>Atom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.AtomImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getAtom()
   * @generated
   */
  int ATOM = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__LEFT = FORM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__RIGHT = FORM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Atom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM_FEATURE_COUNT = FORM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.ParImpl <em>Par</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.ParImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getPar()
   * @generated
   */
  int PAR = 7;

  /**
   * The number of structural features of the '<em>Par</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.ParameterIntImpl <em>Parameter Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.ParameterIntImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getParameterInt()
   * @generated
   */
  int PARAMETER_INT = 8;

  /**
   * The feature id for the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_INT__INT = PAR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parameter Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_INT_FEATURE_COUNT = PAR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.ParameterVarImpl <em>Parameter Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.ParameterVarImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getParameterVar()
   * @generated
   */
  int PARAMETER_VAR = 9;

  /**
   * The feature id for the '<em><b>Up</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_VAR__UP = PAR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parameter Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_VAR_FEATURE_COUNT = PAR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.ParameterPredImpl <em>Parameter Pred</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.ParameterPredImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getParameterPred()
   * @generated
   */
  int PARAMETER_PRED = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_PRED__LEFT = ATOM__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_PRED__RIGHT = ATOM__RIGHT;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_PRED__LIST = ATOM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Low</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_PRED__LOW = ATOM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Parameter Pred</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_PRED_FEATURE_COUNT = ATOM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.mde.datalog.impl.ParamListImpl <em>Param List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.mde.datalog.impl.ParamListImpl
   * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getParamList()
   * @generated
   */
  int PARAM_LIST = 11;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST__LEFT = PAR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST__RIGHT = PAR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Param List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_LIST_FEATURE_COUNT = PAR_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.mde.datalog.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.mde.datalog.Model#getProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Program</em>'.
   * @see org.xtext.mde.datalog.Model#getProgram()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Program();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.Statements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statements</em>'.
   * @see org.xtext.mde.datalog.Statements
   * @generated
   */
  EClass getStatements();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.Comment <em>Comment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comment</em>'.
   * @see org.xtext.mde.datalog.Comment
   * @generated
   */
  EClass getComment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mde.datalog.Comment#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.mde.datalog.Comment#getText()
   * @see #getComment()
   * @generated
   */
  EAttribute getComment_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.Form <em>Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form</em>'.
   * @see org.xtext.mde.datalog.Form
   * @generated
   */
  EClass getForm();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.Assertion <em>Assertion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assertion</em>'.
   * @see org.xtext.mde.datalog.Assertion
   * @generated
   */
  EClass getAssertion();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.Formula <em>Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formula</em>'.
   * @see org.xtext.mde.datalog.Formula
   * @generated
   */
  EClass getFormula();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mde.datalog.Formula#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.mde.datalog.Formula#getLeft()
   * @see #getFormula()
   * @generated
   */
  EReference getFormula_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mde.datalog.Formula#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.mde.datalog.Formula#getRight()
   * @see #getFormula()
   * @generated
   */
  EReference getFormula_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.Atom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atom</em>'.
   * @see org.xtext.mde.datalog.Atom
   * @generated
   */
  EClass getAtom();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.Par <em>Par</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Par</em>'.
   * @see org.xtext.mde.datalog.Par
   * @generated
   */
  EClass getPar();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.ParameterInt <em>Parameter Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Int</em>'.
   * @see org.xtext.mde.datalog.ParameterInt
   * @generated
   */
  EClass getParameterInt();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mde.datalog.ParameterInt#getInt <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int</em>'.
   * @see org.xtext.mde.datalog.ParameterInt#getInt()
   * @see #getParameterInt()
   * @generated
   */
  EAttribute getParameterInt_Int();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.ParameterVar <em>Parameter Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Var</em>'.
   * @see org.xtext.mde.datalog.ParameterVar
   * @generated
   */
  EClass getParameterVar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mde.datalog.ParameterVar#getUp <em>Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Up</em>'.
   * @see org.xtext.mde.datalog.ParameterVar#getUp()
   * @see #getParameterVar()
   * @generated
   */
  EAttribute getParameterVar_Up();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.ParameterPred <em>Parameter Pred</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Pred</em>'.
   * @see org.xtext.mde.datalog.ParameterPred
   * @generated
   */
  EClass getParameterPred();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mde.datalog.ParameterPred#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see org.xtext.mde.datalog.ParameterPred#getList()
   * @see #getParameterPred()
   * @generated
   */
  EReference getParameterPred_List();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.mde.datalog.ParameterPred#getLow <em>Low</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Low</em>'.
   * @see org.xtext.mde.datalog.ParameterPred#getLow()
   * @see #getParameterPred()
   * @generated
   */
  EAttribute getParameterPred_Low();

  /**
   * Returns the meta object for class '{@link org.xtext.mde.datalog.ParamList <em>Param List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param List</em>'.
   * @see org.xtext.mde.datalog.ParamList
   * @generated
   */
  EClass getParamList();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mde.datalog.ParamList#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.mde.datalog.ParamList#getLeft()
   * @see #getParamList()
   * @generated
   */
  EReference getParamList_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.mde.datalog.ParamList#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.mde.datalog.ParamList#getRight()
   * @see #getParamList()
   * @generated
   */
  EReference getParamList_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DatalogFactory getDatalogFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.ModelImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Program</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PROGRAM = eINSTANCE.getModel_Program();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.StatementsImpl <em>Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.StatementsImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getStatements()
     * @generated
     */
    EClass STATEMENTS = eINSTANCE.getStatements();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.CommentImpl <em>Comment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.CommentImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getComment()
     * @generated
     */
    EClass COMMENT = eINSTANCE.getComment();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMENT__TEXT = eINSTANCE.getComment_Text();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.FormImpl <em>Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.FormImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getForm()
     * @generated
     */
    EClass FORM = eINSTANCE.getForm();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.AssertionImpl <em>Assertion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.AssertionImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getAssertion()
     * @generated
     */
    EClass ASSERTION = eINSTANCE.getAssertion();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.FormulaImpl <em>Formula</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.FormulaImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getFormula()
     * @generated
     */
    EClass FORMULA = eINSTANCE.getFormula();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMULA__LEFT = eINSTANCE.getFormula_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMULA__RIGHT = eINSTANCE.getFormula_Right();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.AtomImpl <em>Atom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.AtomImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getAtom()
     * @generated
     */
    EClass ATOM = eINSTANCE.getAtom();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.ParImpl <em>Par</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.ParImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getPar()
     * @generated
     */
    EClass PAR = eINSTANCE.getPar();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.ParameterIntImpl <em>Parameter Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.ParameterIntImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getParameterInt()
     * @generated
     */
    EClass PARAMETER_INT = eINSTANCE.getParameterInt();

    /**
     * The meta object literal for the '<em><b>Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_INT__INT = eINSTANCE.getParameterInt_Int();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.ParameterVarImpl <em>Parameter Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.ParameterVarImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getParameterVar()
     * @generated
     */
    EClass PARAMETER_VAR = eINSTANCE.getParameterVar();

    /**
     * The meta object literal for the '<em><b>Up</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_VAR__UP = eINSTANCE.getParameterVar_Up();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.ParameterPredImpl <em>Parameter Pred</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.ParameterPredImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getParameterPred()
     * @generated
     */
    EClass PARAMETER_PRED = eINSTANCE.getParameterPred();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER_PRED__LIST = eINSTANCE.getParameterPred_List();

    /**
     * The meta object literal for the '<em><b>Low</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_PRED__LOW = eINSTANCE.getParameterPred_Low();

    /**
     * The meta object literal for the '{@link org.xtext.mde.datalog.impl.ParamListImpl <em>Param List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.mde.datalog.impl.ParamListImpl
     * @see org.xtext.mde.datalog.impl.DatalogPackageImpl#getParamList()
     * @generated
     */
    EClass PARAM_LIST = eINSTANCE.getParamList();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM_LIST__LEFT = eINSTANCE.getParamList_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAM_LIST__RIGHT = eINSTANCE.getParamList_Right();

  }

} //DatalogPackage
