/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.Operation#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.Operation#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends Form
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Form)
   * @see org.xtext.mde.datalog.DatalogPackage#getOperation_Left()
   * @model containment="true"
   * @generated
   */
  Form getLeft();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Operation#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Form value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Formula)
   * @see org.xtext.mde.datalog.DatalogPackage#getOperation_Right()
   * @model containment="true"
   * @generated
   */
  Formula getRight();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.Operation#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Formula value);

} // Operation
