/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Par</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getPar()
 * @model
 * @generated
 */
public interface Par extends EObject
{
} // Par
