/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getParam()
 * @model
 * @generated
 */
public interface Param extends Statements
{
} // Param
