/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.ParameterInt#getInt <em>Int</em>}</li>
 * </ul>
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getParameterInt()
 * @model
 * @generated
 */
public interface ParameterInt extends Par
{
  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see org.xtext.mde.datalog.DatalogPackage#getParameterInt_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link org.xtext.mde.datalog.ParameterInt#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

} // ParameterInt
