/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mde.datalog.DatalogPackage#getStatements()
 * @model
 * @generated
 */
public interface Statements extends EObject
{
} // Statements
