/*
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mde.DatalogRuntimeModule;
import org.xtext.mde.DatalogStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DatalogIdeSetup extends DatalogStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DatalogRuntimeModule(), new DatalogIdeModule()));
	}
	
}
