/**
 * generated by Xtext 2.24.0
 */
package org.xtext.mde.datalog.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.mde.datalog.Atom;
import org.xtext.mde.datalog.AtomC;
import org.xtext.mde.datalog.DatalogPackage;
import org.xtext.mde.datalog.Par;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atom C</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mde.datalog.impl.AtomCImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.impl.AtomCImpl#getLp <em>Lp</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.impl.AtomCImpl#getList <em>List</em>}</li>
 *   <li>{@link org.xtext.mde.datalog.impl.AtomCImpl#getRp <em>Rp</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtomCImpl extends MinimalEObjectImpl.Container implements AtomC
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected Atom name;

  /**
   * The default value of the '{@link #getLp() <em>Lp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLp()
   * @generated
   * @ordered
   */
  protected static final String LP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLp() <em>Lp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLp()
   * @generated
   * @ordered
   */
  protected String lp = LP_EDEFAULT;

  /**
   * The cached value of the '{@link #getList() <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getList()
   * @generated
   * @ordered
   */
  protected Par list;

  /**
   * The default value of the '{@link #getRp() <em>Rp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRp()
   * @generated
   * @ordered
   */
  protected static final String RP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRp() <em>Rp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRp()
   * @generated
   * @ordered
   */
  protected String rp = RP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtomCImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DatalogPackage.Literals.ATOM_C;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Atom getName()
  {
    if (name != null && name.eIsProxy())
    {
      InternalEObject oldName = (InternalEObject)name;
      name = (Atom)eResolveProxy(oldName);
      if (name != oldName)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DatalogPackage.ATOM_C__NAME, oldName, name));
      }
    }
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Atom basicGetName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(Atom newName)
  {
    Atom oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DatalogPackage.ATOM_C__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLp()
  {
    return lp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLp(String newLp)
  {
    String oldLp = lp;
    lp = newLp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DatalogPackage.ATOM_C__LP, oldLp, lp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Par getList()
  {
    return list;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetList(Par newList, NotificationChain msgs)
  {
    Par oldList = list;
    list = newList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DatalogPackage.ATOM_C__LIST, oldList, newList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setList(Par newList)
  {
    if (newList != list)
    {
      NotificationChain msgs = null;
      if (list != null)
        msgs = ((InternalEObject)list).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DatalogPackage.ATOM_C__LIST, null, msgs);
      if (newList != null)
        msgs = ((InternalEObject)newList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DatalogPackage.ATOM_C__LIST, null, msgs);
      msgs = basicSetList(newList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DatalogPackage.ATOM_C__LIST, newList, newList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRp()
  {
    return rp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRp(String newRp)
  {
    String oldRp = rp;
    rp = newRp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DatalogPackage.ATOM_C__RP, oldRp, rp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DatalogPackage.ATOM_C__LIST:
        return basicSetList(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DatalogPackage.ATOM_C__NAME:
        if (resolve) return getName();
        return basicGetName();
      case DatalogPackage.ATOM_C__LP:
        return getLp();
      case DatalogPackage.ATOM_C__LIST:
        return getList();
      case DatalogPackage.ATOM_C__RP:
        return getRp();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DatalogPackage.ATOM_C__NAME:
        setName((Atom)newValue);
        return;
      case DatalogPackage.ATOM_C__LP:
        setLp((String)newValue);
        return;
      case DatalogPackage.ATOM_C__LIST:
        setList((Par)newValue);
        return;
      case DatalogPackage.ATOM_C__RP:
        setRp((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DatalogPackage.ATOM_C__NAME:
        setName((Atom)null);
        return;
      case DatalogPackage.ATOM_C__LP:
        setLp(LP_EDEFAULT);
        return;
      case DatalogPackage.ATOM_C__LIST:
        setList((Par)null);
        return;
      case DatalogPackage.ATOM_C__RP:
        setRp(RP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DatalogPackage.ATOM_C__NAME:
        return name != null;
      case DatalogPackage.ATOM_C__LP:
        return LP_EDEFAULT == null ? lp != null : !LP_EDEFAULT.equals(lp);
      case DatalogPackage.ATOM_C__LIST:
        return list != null;
      case DatalogPackage.ATOM_C__RP:
        return RP_EDEFAULT == null ? rp != null : !RP_EDEFAULT.equals(rp);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (lp: ");
    result.append(lp);
    result.append(", rp: ");
    result.append(rp);
    result.append(')');
    return result.toString();
  }

} //AtomCImpl
